extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
  - 'eslint-plugin-mozilla'
rules:
  no-unused-vars: warn
  semi: warn
